name: Build and Run

on:
  push:
  pull_request:

jobs:
  build-run:
    name: Build and run with startup msg verification
    uses: havencarlson/cFS/.github/workflows/build-run-app.yml@workflow-ubuntu-update
